version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: pg_container0
    restart: always
    environment:
#      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5435:5432"